apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-feed
  name: api-feed
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: api-feed
